apiVersion: v1
kind: ConfigMap
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "bitcoind.labels" . | indent 4 }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  {{- (.Files.Glob "check_node_health.sh").AsConfig | nindent 2 }}
---
