apiVersion: v1
kind: ConfigMap
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "bitcoind.labels" . | indent 4 }}
data:
  {{ .Values.bitcoind.configurationFileName }}: |-
  {{- include "bitcoind/templates/_bitcoin.conf" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  check_node_health.sh: |
  {{- include "bitcoind/templates/_check_node_health.sh" . | nindent 4 }}
---
