apiVersion: v1
kind: ConfigMap
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "bitcoind.labels" . | indent 4 }}
data:
  {{ .Values.bitcoind.configurationFileName }}: |-
  {{- include (print $.Template.BasePath "/_bitcoin.conf") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  check_node_health.sh: |
  {{- include (print $.Template.BasePath "/_check_node_health.sh") . | nindent 4 }}
---
