steps:
  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - package
      - charts/$_CHART_NAME
    id: 'helm package'
    env:
      - GCS_PLUGIN_VERSION=0.2.2
      - HELMFILE_VERSION=v0.85.3
      - HELM_REPO_NAME=$_HELM_REPO_NAME
      - HELM_REPO_URL=$_HELM_REPO_URL

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - plugin
      - install
      - https://github.com/mbenabda/helm-local-chart-version
      - --version
      - v0.0.6
    id: 'add version plugin'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - helm local-chart-version get -c charts/$_CHART_NAME > $_ARTIFACT_FILENAME
    id: 'save version to artifact'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - helm gcs push ${_CHART_NAME}-$(cat $_ARTIFACT_FILENAME).tgz $_HELM_REPO_NAME
    id: 'helm push'

substitutions:
 _REGISTRY: gcr.io
 _ENV: dev
 _CHART_NAME: bitcoind
 _HELM_REPO_NAME: blockchain-k8s
 _HELM_REPO_URL: gs://blockchain-k8s/charts
 _ARTIFACT_URL: gs://artifacts-/versions/
 _ARTIFACT_FILENAME: bitcoind-chart-version
options:
  env:
   - SKIP_CLUSTER_CONFIG=true

artifacts:
  objects:
    location: ${_ARTIFACT_URL}/${_ENV}/
    paths:
      - $_ARTIFACT_FILENAME

