# PVC - PROD ETH eth-prod-ss-1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eth-regional-pvc-1-2 # was eth-regional-pvc-1-1, previously eth-regional-pvc-1
spec:
# We leave storageClassName empty so that default storage class is not used
  storageClassName: ""
  volumeName: eth-regional-pv-1-2 # was eth-regional-pv-1-1, previously was eth-regional-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000G
---
# PV - PROD ETH eth-prod-ss-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eth-regional-pv-1-2 # was eth-regional-pv-1-1
spec:
  storageClassName: ""
  capacity:
    storage: 5000G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: eth-region-bc-pdd-1-2 # bootstrapping from ss-2 to. Includes Feb 26 chain data. 
#    pdName: eth-region-bc-pdd-1-1 # depricated Feb 26, includes Feb 9 chain data
#    pdName: eth-region-bc-pdd-1 # depricated Feb 26
#    pdName: eth-classic-staging-1
    fsType: ext4
---
# PVC - PROD ETH 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eth-regional-pvc-2
spec:
# We leave storageClassName empty so that default storage class is not used
  storageClassName: ""
  volumeName: eth-regional-pv-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000G
---
# PV - PROD ETH
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eth-regional-pv-2
spec:
  storageClassName: ""
  capacity:
    storage: 5000G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: eth-region-bc-pdd-2
#    pdName: eth-classic-staging-1
    fsType: ext4