## ConfigMap FOR ETH PROD
apiVersion: v1
kind: ConfigMap
metadata:
  name: parity-config
  namespace: default
data:
  parity.toml: |
    [parity]
    # Parity continously syncs the chain
    mode = "active"
    # Stable
    release_track = "stable"

    # Blockchain and settings will be stored in /data.
    base_path = "/data"

    [network]
    # Parity will sync by downloading latest state first. Node will be operational in couple minutes.
    warp = false
    # Parity will try to maintain connection to at least 250 peers.
    min_peers = 250
    # Parity will maintain at most 300 peers.
    max_peers = 300

    [rpc]
    #  JSON-RPC will be listening for connections on IP all.
    interface = "all"
    # Only selected APIs will be exposed over this interface.
    apis = ["eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "web3"]
    # Threads for handling incoming connections for HTTP JSON-RPC server.
    server_threads = 6
    # Turn on additional processing threads for JSON-RPC servers (all transports). Setting this to a non-zero value allows parallel execution of cpu-heavy queries.
    processing_threads = 7

    [websockets]
    # UI won't work and WebSockets server will be not available.
    disable = true

    [footprint]
    # Compute and Store tracing data. (Enables trace_* APIs).
    tracing = "on"
    # Increase performance on SSD.
    db_compaction = "ssd"
    # Keep all state trie data. No pruning.
    pruning = "archive"
    # Number of threads will vary depending on the workload. Not guaranteed to be faster.
    scale_verifiers = true
    # Will keep up to 1000MB data in Database cache.
    cache_size_db = 1000

    [snapshots]
    disable_periodic = false

    [misc]
    # Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
    logging = "info"
    log_file = "/data/parity.log"
    color = true
---
## PROD STATEFULSET FOR ETH
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-prod-ss-1 # Statefulset Name
spec:
  selector:
    matchLabels:
      app: eth-prod-app-1 # has to match .spec.template.metadata.labels
  serviceName: "eth-prod-ss-1"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: eth-prod-app-1 # pod templates label selector has to match .spec.selector.matchLabels
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - us-central1-b
      terminationGracePeriodSeconds: 10
      containers:
      - name: parity
        image: gcr.io/crypto-etl-clients/parity:v2.4.6 # [may 19]; upgraded; was v2.2.10 # [Feb 26] Was 2.3.3. Now 2.2.10. security patch. parity stable Feb 16 2019
        args: ["--config=/config/parity.toml"]
        resources:
          requests:
            cpu: "2800m" 
            memory: "10000Mi"
          limits:
            cpu: "3000m" 
            memory: "12000Mi"
#        command: ["/bin/parity"]
#        args: ["--jsonrpc-interface=all", "--jsonrpc-apis=all", "--jsonrpc-port=8545", "--tracing=on", "-l info", "--max-peers=300", "--cache-size=10000", "--scale-verifiers", "--min-peers=250", "--pruning=archive", "--db-compaction=ssd", "--base-path=/data"]
        ports:
        - containerPort: 8545
          name: web-socket
        - containerPort: 8546
          name: jsonrpc
        - containerPort: 30303
          protocol: UDP
        volumeMounts:
        - name: parity-config
          mountPath: /config
        - name: eth-prod-mount-1
          mountPath: /data
      initContainers:
      - name: setup
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: eth-prod-mount-1
          mountPath: /data
      volumes:
        - name: parity-config
          configMap:
            name: parity-config 
        - name: eth-prod-mount-1
          persistentVolumeClaim:
            claimName: eth-regional-pvc-1-2 # was eth-regional-pvc-1-1, previously eth-regional-pvc-1
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-prod-ss-2 # Statefulset Name
spec:
  selector:
    matchLabels:
      app: eth-prod-app-2 # has to match .spec.template.metadata.labels
  serviceName: "eth-prod-ss-2"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: eth-prod-app-2 # pod templates label selector has to match .spec.selector.matchLabels
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - us-central1-c
      terminationGracePeriodSeconds: 10
      containers:
      - name: parity
        image: gcr.io/crypto-etl-clients/parity:v2.3.2 # requires security patch update
        resources:
          requests:
            cpu: "2800m"
            memory: "10000Mi" # was 11000
          limits:
            cpu: "3000m"
            memory: "12000Mi" # was 12000
        command: ["./entrypoint.sh"]
        args: ["--jsonrpc-interface=all", "--jsonrpc-apis=all", "--jsonrpc-port=8545", "--tracing=on", "--base-path=/data", "--cache-size=10000", "--scale-verifiers", "-l info", "--pruning=archive", "--db-compaction=ssd", "--max-peers=300", "--min-peers=250"]
        ports:
        - containerPort: 8545
          name: web-socket
        - containerPort: 8546
          name: jsonrpc
        - containerPort: 30303
          protocol: UDP
        volumeMounts:
        - name: eth-prod-mount-2
          mountPath: /data
      initContainers:
      - name: setup
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: eth-prod-mount-2
          mountPath: /data
      volumes:
        - name: eth-prod-mount-2
          persistentVolumeClaim:
            claimName: eth-regional-pvc-2