apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-regional-us-central1-bc
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: us-central1-b, us-central1-c
