apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
{{ include "theta.labels" . | indent 4 }}
data:
  config.yaml: |
    {{- include (print $.Template.BasePath "/_config.yaml") . | nindent 4 }}
