apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-secret"
  labels:
{{ include "theta.labels" . | indent 4 }}
type: Opaque
data:
  node_passwd: {{ .Values.theta.node_passwd | b64enc  }}
