{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "theta.serviceAccountName" . }}
  labels:
{{ include "theta.labels" . | indent 4 }}
{{- end -}}
