steps:
  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - tar czf ${_CHART_NAME}-${SHORT_SHA}.tar.gz -C charts/$_CHART_NAME .
    id: 'helm archive'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - gcs
      - push
      - ${_CHART_NAME}-${SHORT_SHA}.tar.gz
      - $_HELM_REPO_NAME
    id: 'helm push'
    env:
      - GCS_PLUGIN_VERSION=0.2.1
      - HELMFILE_VERSION=v0.85.3
      - HELM_REPO_NAME=$_HELM_REPO_NAME
      - HELM_REPO_URL=gs://artifacts-$PROJECT_ID/charts

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - plugin
      - install
      - https://github.com/mbenabda/helm-local-chart-version
      - --version
      - v0.0.6
    id: 'add version plugin'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - helm local-chart-version get -c charts/$_CHART_NAME > $_ARTIFACT_FILENAME
    id: 'save artifact'

substitutions:
 _REGISTRY: gcr.io
 _ENV: dev
 _CHART_NAME: bitcoind
 _HELM_REPO_NAME: baas-gke-dev
 _ARTIFACT_FILENAME: bitcoind-chart-version

options:
  env:
   - CLOUDSDK_COMPUTE_ZONE=us-central1-b
   - CLOUDSDK_CONTAINER_CLUSTER=baas0

artifacts:
  objects:
    location: gs://artifacts-${PROJECT_ID}/versions/${_ENV}/
    paths:
      - $_ARTIFACT_FILENAME

