# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
terminationGracePeriodSeconds: 30
image:
  repository: arilot/docker-bitcoind
  tag: 0.18.0
  pullPolicy: IfNotPresent

service:
  rpcPortName: &rpcPortName jsonrpc
  rpcPort: &rpcPort 8332
  p2pPort: &p2pPort 8333
  p2pPortName: &p2pPortName p2p
  ports:
    - name: *rpcPortName
      port: *rpcPort
      targetPort: *rpcPortName
    - name: *p2pPortName
      port: *p2pPort
      targetPort: *p2pPortName

externalLB: false
externalLBSourceRanges: {}
#  - 203.0.113.2/32
#  - 203.0.113.3/32

externalLBp2p: false
externalLBp2pIP: 198.51.100.1
internalLB: false


persistence:
  enabled: true
#  storageClass: "default"
  accessMode: ReadWriteOnce
  size: "500Gi"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: "2800m"
    memory: "10000Mi"
  limits:
    cpu: "3000m"
    memory: "12000Mi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "bitcoind"
          topologyKey: failure-domain.beta.kubernetes.io/zone

bitcoind:
  base_path: "/data"

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser=rpcuser
    rpcpassword=rpcpassword
    rpcbind=0.0.0.0
    rpcallowip=::/0
    txindex=1
    disablewallet=1
    # externalip=198.51.100.1

livenessProbe:
  initialDelaySeconds: 600
  periodSeconds: 600
  timeoutSeconds: 500
  failureThreshold: 2
