apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-ss
spec:
  serviceName: "eth-ss-1"
  replicas: 1 # by default is 1
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - us-central1-b
      terminationGracePeriodSeconds: 10
      containers:
      - name: parity
        image: gcr.io/crypto-etl-clients/parity:v2.4.6
        args: ["--config=/config/parity.toml"]
        resources:
          requests:
            cpu: "2800m" 
            memory: "10000Mi"
          limits:
            cpu: "3000m" 
            memory: "12000Mi"
        ports:
        - containerPort: 8545
          name: web-socket
        - containerPort: 8546
          name: jsonrpc
        - containerPort: 30303
          protocol: UDP
        volumeMounts:
        - name: parity-config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: eth-mount
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_health.sh
            - http://127.0.0.1:8545
            - "300"
            - last_synced_block.txt
          initialDelaySeconds: 300
          periodSeconds: 300
          timeoutSeconds: 10
          failureThreshold: 2
      initContainers:
      - name: setup
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: eth-mount
          mountPath: /data
      volumes:
        - name: parity-config
          configMap:
            name: parity-config
        - name: scripts
          configMap:
            name: scripts
        - name: eth-mount
          persistentVolumeClaim:
            claimName: eth-regional-pvc
